<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Event;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function eventDateAscendingOrder()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('d')
            ->from('AppBundle:Event', 'd')
            ->orderBy('d.date', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
